exclude_files = ["**/generated/**", "tmp_metadata.json"]
active_profile = "unstable"

[parameters.P001]
ahead_significant_diff = 2

[parameters.W002]
stale_after_days = 1

[profiles.unstable]
ignore = ["W002", "P017"]
fail_on_warnings = false
fail_on_pitfalls = false

[profiles.unstable.parameters.P001]
ahead_significant_diff = 10

[profiles.unstable.parameters.W002]
stale_after_days = 10

[profiles.prerelease]
ignore = [] # remove all ignores for prerelease profile
fail_on_warnings = true
fail_on_pitfalls = true

[profiles.prerelease.parameters.P001]
ahead_significant_diff = 2

[profiles.prerelease.parameters.W002]
stale_after_days = 1