name: RsMetaCheck Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, labeled, unlabeled] # Needed to catch label changes
 

jobs:
  analyze-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Determine Environment
        id: check_label
        run: |
          if echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -q "prerelease"; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Run RSMetacheck
        uses: SoftwareUnderstanding/rs-metacheck-action@0.3.6
        with:
          input: "https://github.com/SoftwareUnderstanding/rsmetacheck-bot"
          branch: $GITHUB_REF
          pitfalls_output: ./pitfalls_output
          verbose: true
          config: "./.github/workflows/rsmetacheck.toml"
          config_profile: ${{ env.IS_PRERELEASE == 'true' && 'prerelease' || 'unstable' }}
      
      - name: Upload Pitfalls Output
        uses: actions/upload-artifact@v7
        if: always() # to ensure the artifact is uploaded even if the previous step fails
        with:
          name: pitfalls output 
          path: ./pitfalls_output/       # The path to the file or directory you want to save
          retention-days: 5